FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Expose Hardhat node port
EXPOSE 8545

# Default command: run local node
CMD ["npx", "hardhat", "node"]
